name: CI

permissions: {}
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Deny of Service Attack Project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          cd dos-attack
          forge install foundry-rs/forge-std --no-git
          
      - name: Show Forge version
        run: |
          cd dos-attack
          forge --version

      - name: Run Forge fmt
        run: |
          cd dos-attack
          forge fmt --check

      - name: Run Forge build
        run: |
          cd dos-attack
          forge build --sizes

      - name: Run Forge tests
        run: |
          cd dos-attack
          forge test -vvv
        
      - name: Run Forge coverage
        run: |
          cd dos-attack
          forge coverage --report summary
